import fs from 'node:fs'
const built=fs.readFileSync(new URL('../../catalog/desktop/plugin.js',import.meta.url),'utf8')
const source=fs.readFileSync(new URL('./plugin.src.js',import.meta.url),'utf8')
const failures=[]
const has=(name,text,where=source)=>{if(!where.includes(text))failures.push(name)}
has('bounded force layout','function layoutGraph(data)')
has('spatial label collision selection','function spatialLabelSelection')
has('DPR-safe canvas sizing','window.devicePixelRatio')
has('zoom-scaled label font','baseAtFit*(zoom/fitScale)')
has('DPR-aligned label transform','g.setTransform(d,0,0,d,0,0)')
has('plate-free outlined labels','g.strokeText(title,tx,ty)')
if(source.includes('g.fillRect(box.x,box.y,box.w,box.h)')||source.includes('g.strokeRect(box.x+.5'))failures.push('rectangular label plates remain')
if(/\?\.\d+/.test(source)||/\?\.\d+/.test(built))failures.push('invalid numeric optional chaining remains')
has('no numeric optional chaining','incident?0.88:0.08')
has('pointer-centred wheel zoom','zoomAt(Math.exp(-e.deltaY*.001),sx,sy)')
has('non-passive native wheel listener',"addEventListener('wheel',wheel,{passive:false})")
has('background pan','s.tx+=dx;s.ty+=dy')
has('node drag','d.node.x+=dx/s.scale;d.node.y+=dy/s.scale')
has('click node opens note','if(d?.node&&!d.moved)open(d.node.path)')
has('open note switches to notes view',"const go=()=>{setView('notes');setTabs")
has('click vs drag slop','>8)d.moved=true')
has('explicit Fit','onClick:fit')
has('resize ignores unusable host','if(rawW<100||rawH<100)return')
has('resize preserves world centre','worldX=(s.w/2-s.tx)/s.scale')
has('fit/draw refs','fitRef.current=fit')
has('ref-based try fit','fitRef.current()')
has('explicit canvas height','canvasHeight')
has('global scope',"children:'Global'")
has('local scope',"children:'Local'")
has('filter','Filter graph')
has('Key labels',"children:'Key'")
has('More labels',"children:'More'")
has('All labels',"children:'All'")
has('default More labels',"useState('more')")
has('Key not persisted',"useEffect(()=>{setLabelMode('more')},[ctx])")
if(/graphDiag|setGraphDiag|canvasCount|live dom/.test(source))failures.push('temporary diagnostics remain')
if(/cytoscape|runObsidianLayout|new ForceGraph|force-graph/.test(source)||/Cytoscape\.js/.test(built))failures.push('abandoned graph engine remains')
const imports=[...built.matchAll(/(?:from\s*|import\s*)["']([^"']+)["']/g)].map(m=>m[1])
const allowed=new Set(['@hermes/plugin-sdk','react','react/jsx-runtime'])
const bad=imports.filter(x=>!allowed.has(x))
if(bad.length)failures.push('unsupported imports remain: '+bad.join(', '))
if(failures.length){console.error('Brain graph regression check failed:\n- '+failures.join('\n- '));process.exit(1)}
console.log('Brain graph regression check passed.')
